registry:
        image: registry:2
        ports:
                - 127.0.0.1:5000:5000
        environment:
                REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
                - ./data:/data
registy:

